---
# superbox :: tasks

  - name: Setting host become password from vault, if it exists
    when: ( lookup('vars', 'vault_' + inventory_hostname + '_become_pass', default=false) )
    vars:
      _pass: "{{ lookup('vars', 'vault_' + inventory_hostname + '_become_pass') }}"
    set_fact:
      ansible_become_pass: "{{ _pass }}"
