---
- name: Build Vagrantboxes
  hosts: localhost
  roles:
    - sandbox
  vars_prompt:
    - name: box_allow_fetch
      prompt: Allow fetch tasks?
      default: true
      private: no
  tasks:
    - name: Checking availability of networked resources
      fail:
        msg: This play requires networked resources
      when: not (box_has_internet or box_has_netmirror)
