---
- name: Provision host by name
  hosts: "{{ _target }}"
  roles:
    - common
  vars_prompt:
    - name: _target
      prompt: Provision host
      default: "localhost"
      private: no
  tasks:

    - name: Provisioning standalone host
      when: ( not box_has_internet )
      include_role:
        name: "lonelybox"

    - name: Provisioning rootless host
      when: ( not box_has_sudo )
      include_role:
        name: "uselessbox"

    - name: Provisioning basic devbox host
      include_role:
        name: "devbox"

    - name: Provisioning advanced roles
      when: ( box_has_sudo)
      include_role:
        name: "{{ _role_name }}"
      loop_control:
        loop_var: _role_name
      with_items:
        - sandbox
        - kubebox
