---
- name: Prepare vagrant box factory
  hosts: "{{ _target }}"
  roles:
    - common
  vars_prompt:
    - name: _target
      prompt: Prepare vagrant box factory on host
      default: "localhost"
      private: no
    - name: _no_fetch
      prompt: Skip fetch tasks?
      default: no
      private: no
  tasks:
    - name: Verifying permitted fetch protocols
      when: ( _no_fetch )
      set_fact:
        box_fetch_allowlist: [ ]

    - name: Checking availability of networked resources
      fail:
        msg: This play requires networked resources
      when: not (box_has_internet or box_has_netmirror)

    - name: Including sandbox role
      include_role:
        name: "sandbox"
