---
- name: Prepare repository patches
  hosts: "{{ _target }}"
  roles:
    - common
  vars_prompt:
    - name: _target
      prompt: Format patches on host
      default: "localhost"
      private: no
  tasks:
    - name: Searching for patch tasks across roles
      find:
        paths: "{{ item }}"
        patterns: "patch.yml"
        recurse: yes
        file_type: "file"
      with_items:
        - "roles"
        - "{{ box_local_roles_path }}"
      register: _role_paths

    - name: Formatting patches across roles
      include_role:
        name: "{{ _role }}"
        tasks_from: patch
      vars:
        _role: "{{ _role_path.1.path
                   | regex_search('.+/(.+)/tasks/patch.yml', '\\1')
                   | first
                }}"
      with_subelements:
        - "{{ _role_paths.results | selectattr('matched', 'greaterthan', 0) }}"
        - "files"
      loop_control:
        loop_var: _role_path
