---
- name: Prepare Airgap
  hosts: localhost
  roles:
    - fetchbox
  tasks:
    - name: "Pushing {{ box_local_cache_path }} to {{ box_gapmirror_uri }}"
      when: (box_has_gapmirror)
      command: "rsync -avSHP --delete {{ box_local_cache_path }}/ {{ box_gapmirror_uri }}"
