---
- name: Prepare Airgap
  hosts: localhost
  roles:
    - fetchbox
  vars_prompt:
    - name: box_allow_fetch
      prompt: Allow fetch tasks?
      default: true
      private: no
  tasks:
    - name: Pushing {{ box_cache_path }} to {{ box_mirror_path }}
      when: (box_has_mirror)
      command: "rsync -avSHP --delete {{ box_cache_path }}/ {{ box_mirror_path }}"

