---
# ansible-playbook -e 'ansible_python_interpreter=/usr/bin/python' -K playbook/provision-standalone.yml
- name: Provision Standalone
  hosts: localhost

  tasks:
    - name: Locate workspace
      stat:
        path: "{{ ansible_env.HOME }}/workspace"
      register: workspace

    - name: Add mirrorhost to /etc/hosts
      become: true
      lineinfile:
        path: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        regexp: '^127\.0\.0\.1'
        line: 127.0.0.1 localhost mirrorhost localhost.localdomain

    - name: Check mirror availability
      uri:
        url: http://mirrorhost:8080
        follow_redirects: none
        method: GET
      register: _result
      until: _result.status == 200
      retries: 3
      delay: 5 # seconds

    - name: Disable all repositories by default
      become: true
      command: yum-config-manager --disable *

    - name: Add CentOS-7 mirror repositories to /etc/yum.repos.d/
      become: true
      blockinfile:
        path: /etc/yum.repos.d/CentOS-Mirror.repo
        create: yes
        owner: root
        group: root
        mode: '0644'
        block: |
          [mirror-base]
          name=CentOS-$releasever - Base Mirror
          baseurl=http://mirrorhost:8080/system/centos/$releasever/os/$basearch/
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          gpgcheck=1
          enabled=1

          [mirror-updates]
          name=CentOS-$releasever - Updates Mirror
          baseurl=http://mirrorhost:8080/system/centos/$releasever/updates/$basearch/
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          gpgcheck=1
          enabled=1

          [mirror-extras]
          name=CentOS-$releasever - Extras Mirror
          baseurl=http://mirrorhost:8080/system/centos/$releasever/extras/$basearch/
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
          gpgcheck=1
          enabled=1

          [mirror-epel]
          name=EPEL-$releasever - $basearch Mirror
          baseurl=http://mirrorhost:8080/system/fedora-epel/$releasever/$basearch/
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
          gpgcheck=1
          enabled=1

          [mirror-centos-sclo-rh]
          name=CentOS-7 - SCLo rh Mirror
          baseurl=http://mirrorhost:8080/system/centos/$releasever/sclo/$basearch/rh/
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
          gpgcheck=1
          enabled=1

    - name: Add Additional Repositories
      become: true
      package:
        name:
          - centos-release-scl
          - epel-release
        state: present

    # yumdb search command_line install*
    # yumdb search from_repo <repo_name>
    - name: Verify base packages
      become: true
      package:
        name:
          - python
          - python3
          - git
          - rsync
          - curl
        state: present

    - name: Verify development packages
      become: true
      package:
        name:
          - "@Development tools"
        state: present

    - name: Update installed packages to latest
      become: true
      package:
        name: '*'
        state: latest

    - name: Clone dotfiles
      when: (workspace.stat.exists)
      git:
        repo: http://mirrorhost:8080/github/lenzomj/dotfiles.git
        dest: "{{ workspace.stat.path }}/dotfiles"
        clone: yes
        update: yes
