---
# ansible-playbook -e 'ansible_python_interpreter=/usr/bin/python' -K playbook/provision-standalone.yml
- name: Provision Standalone
  hosts: localhost
  roles:
    - lonelybox
    - devbox
    - sandbox
    - kubebox
