- hosts: localhost
  roles:
    - common
  tasks:
    - name: Searching for encryption tasks across roles
      find:
        paths: "{{ item }}"
        patterns: "rekey.yml"
        recurse: yes
        file_type: "file"
      with_items:
        - "roles"
        - "roles_extended"
      register: _role_paths

      #TODO: Allow selection to rekey individual roles
    - name: "Rekey vault data for which roles?"
      when: false
      pause:
        prompt: "Vault ID(s)"
        echo: true
      register: _vault_ids

    - name: Rekeying vault data required for other roles
      include_role:
        name: "{{ _role }}"
        tasks_from: rekey
        vars_from: vault
      vars:
        _role: "{{ _role_path.1.path
                   | regex_search('.+/(.+)/tasks/rekey.yml', '\\1')
                   | first
                }}"
      with_subelements:
        - "{{ _role_paths.results | selectattr('matched', 'greaterthan', 0) }}"
        - "files"
      loop_control:
        loop_var: _role_path
