- hosts: localhost
  tasks:

    - name: Download
      command: "{{ ansible_python_interpreter }} -m pip download {{ item }}"
      args:
        chdir: "{{ box_cache_path }}/pypi.org"
      with_items:
        - ansible
        - sphinx
