#!/usr/bin/env bash

TEST_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

bats "${TEST_DIR}/test_harness.bats"
bats "${TEST_DIR}/test_parse.bats"
bats "${TEST_DIR}/test_setup_env.bats"
