---
# host_vars :: galactica

###############################################################################
# Host-Specific Resources
###############################################################################

# Override
box_airgap_mount_paths:
  - /mnt/Fortress
