---
# host_vars :: pegasus

###############################################################################
# Host-Specific Resources
###############################################################################

# Override
box_airgap_mount_paths:
  - /media/{{ lookup('env', 'USER') }}/Fortress

pegasus:
  vault_vars:
    - vault_pegasus_become_pass
