---
# host_vars :: triton

###############################################################################
# Host-Specific Resources
###############################################################################

# Override
box_airgap_mount_paths:
  - /run/media/{{ lookup('env', 'USER') }}/Fortress

box_fetch_allowlist:
  - 'get'
  - 'git'
  - 'pip'
