---
# devbox :: fetch

  - name: Finding python package requirements file
    stat:
      path: "{{ role_path }}/files/pypi_packages.txt"
    register: _reqs
    failed_when: (not _reqs.stat.exists)

  - import_role:
      name: library
      tasks_from: fetch-repositories
    vars:
      a_repository_list: "{{ devbox_repositories }}"

  - import_role:
      name: library
      tasks_from: fetch-pypackages
    vars:
      a_requirements_file: "{{ _reqs }}"
