---
# devbox :: fetch

  - name: Fetching devbox repositories from an upstream source
    import_role:
      name: library
      tasks_from: fetch-repositories
    vars:
      a_repository_list: "{{ devbox_repositories }}"
