---
# devbox role (fetch)

  - name: Fetching devbox repositories from upstream source
    when: (box_has_internet and box_has_local_mirror)
    git:
      repo: "{{ lookup('dict', item).value.upstream }}"
      dest: "{{ box_local_mirror_path }}/{{ lookup('dict', item).value.mirror }}"
      bare: yes
      clone: yes
      update: yes
    loop: "{{ devbox_git_repos }}"
