---
# devbox :: fetch

  - import_role:
      name: library
      tasks_from: fetch-repositories
    vars:
      a_repository_list: "{{ devbox_repositories }}"

  ########################

  # TODO: Make generic
  - name: Creating cache directories as required
    file:
      path: "{{ box_cache_path }}/pypi.org"
      state: directory

  # TODO: Make generic
  - name: Fetch pypi packages from an upstream source
    when: (box_has_internet)
    command: "{{ ansible_python_interpreter }} -m pip download {{ item }}"
    args:
      chdir: "{{ box_cache_path }}/pypi.org"
    with_items:
      - ansible
      - ansible-lint
      - sphinx
    register: _result
    changed_when: (_result.stdout | regex_search('Saved'))
