---
# devbox :: main

  - include: fetch.yml

  - name: Cloning repositories from an upstream source
    import_role:
      name: library
      tasks_from: clone-repositories
    vars:
      a_repository_list: "{{ devbox_repositories }}"
