---
# lonelybox :: vars

lonelybox:
  resources: [ ]
  paths:
    mirrorlists: "/etc/yum.repos.d/mirrors"
  mirrors:
    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/RPM-GPG-KEY-CentOS-7"
      handlers: rsync

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/os/"
      handlers: rsync

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/updates/"
      handlers: rsync

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/extras/"
      handlers: rsync

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/sclo/x86_64/rh/"
      handlers: rsync

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/fedora-epel/RPM-GPG-KEY-EPEL-7"
      handlers: rsync

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/fedora-epel/7/x86_64/"
      handlers: rsync
      args:
        options: "--exclude=debug --exclude=drpms"

    - mirror: mirror.ctan.org
      upstream: "rsync://mirrors.rit.edu/CTAN/systems/texlive/tlnet/"
      handlers: rsync

    - mirror: download.docker.com
      upstream: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      handlers: wget
      args:
        options: "--reject='index.html'"
