---
# lonelybox :: vars

lonelybox:
  resources: [ ]
  paths:
    mirrorlists: "/etc/yum.repos.d/mirrors"
  mirrors:
    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/RPM-GPG-KEY-CentOS-7"

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/os/"

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/updates/"

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/extras/"

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/centos/7/sclo/x86_64/rh/"

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/fedora-epel/RPM-GPG-KEY-EPEL-7"

    - mirror: mirror.centos.org
      upstream: "rsync://mirror.cs.pitt.edu/fedora-epel/7/x86_64/"
      options: "--exclude=debug --exclude=drpms"

    - mirror: mirror.ctan.org
      upstream: "rsync://mirrors.rit.edu/CTAN/systems/texlive/tlnet/"
