---
# fetchbox :: tasks

  - name: Fetching resources required for other roles
    include_role:
      name: "{{ role }}"
      tasks_from: fetch
    with_items:
      - devbox
      - sandbox
    loop_control:
      loop_var: role

  - import_tasks: "{{ box_task_library }}/sync-mirror.yml"
    vars:
      a_mirror_list: "{{ fetchbox_mirrors }}"
