---
# fetchbox :: tasks

  - import_tasks: "{{ box_task_library }}/fetch-resources.yml"
    vars:
      resources: "{{ fetchbox.resources }}"

  - name: Searching for fetchable tasks across roles
    find:
      paths: "{{ item }}"
      patterns: "fetch.yml"
      recurse: yes
      file_type: "file"
    with_items:
      - "roles"
      - "roles_extended"
    register: _role_paths

  - name: Fetching resources required for other roles
    include_role:
      name: "{{ _role }}"
      tasks_from: fetch
    vars:
      _role: "{{ _role_path.1.path
                 | regex_search('.+/(.+)/tasks/fetch.yml', '\\1')
                 | first
              }}"
    with_subelements:
      - "{{ _role_paths.results | selectattr('matched', 'greaterthan', 0) }}"
      - "files"
    loop_control:
      loop_var: _role_path
