---

  # TODO: Fetch all roles regardless of whether this host has them
  - name: Fetch resources required for each role
    include_role:
      name: "{{ role }}"
      tasks_from: fetch
    loop: "{{ ansible_play_role_names }}"
    loop_control:
      loop_var: role
