#!/usr/bin/env python2
#vi: set ft=python

from __future__ import print_function

import argparse
import os.path
import sys
import shlex
import subprocess
import urlparse

def handle_with(key, args):
    return ["pushd '{0}' >/dev/null;".format(args)]

def handle_end(key, args):
    return ["popd &> /dev/null;"]

def handle_git(key, args):
    cmd = """
    if [[ ! -d "{local}" ]]; then
      echo "Mirroring {remote} ..." >&2
      git clone --mirror "{remote}" "{local}"
    else
      pushd "{local}" &> /dev/null;
        echo "Updating {local} ..." >&2
        git remote update
      popd &> /dev/null;
    fi
    """
    local = ""
    remote = ""
    if key == 'github':
        remote = "https://github.com/{0}".format(args)
        local = args
    else:
        url = urlparse.urlsplit(args)
        remote = args
        local = url.path.lstrip('/')
    return [cmd.format(local=local, remote=remote)]

def handle_get(key, args):
    cmd = """
    echo "Downloading {remote} ..." >&2
    curl -# -L "{remote}" -o "{local}"
    """
    url = urlparse.urlsplit(args)
    remote = url.geturl()
    local = os.path.basename(url.path)
    return [cmd.format(local=local, remote=remote)]

def handle_rsync(key, args):
    cmd = """
    echo "Syncing {remote} ..." >&2
    rsync -avSHP --delete {flags} {remote} {local} >&2
    """
    args = args.split()
    url = urlparse.urlsplit(args.pop()) # URI is always last
    remote = url.geturl()
    local = url.path.lstrip('/')
    flags = ' '.join(args)
    return [cmd.format(local=local, remote=remote, flags=flags)]

def translate(directive):
    handlers = { 'with'   : handle_with,
                 'end'    : handle_end,
                 'github' : handle_git,
                 'git'    : handle_git,
                 'get'    : handle_get,
                 'rsync'  : handle_rsync }

    key = directive[0].lower()
    args = directive[1]
    return handlers[key](key, args)

def read_manifest(filestream):
    script = []
    lex = shlex.shlex(filestream, posix=True)
    lex.whitespace_split = True
    for token in lex:
        token = os.path.expandvars(token)
        directive = token.split(':', 1)
        if len(directive) == 1:
            directive.append(None)
        script.extend(translate(directive))
    return script

def execute(script):
    p = subprocess.Popen(script,
                         executable='/bin/bash',
                         shell=True,
                         stderr=subprocess.PIPE,
                         stdout=None)

    for stderr_line in iter(p.stderr.readline, ""):
        yield stderr_line
    p.stderr.close()
    rc = p.wait()
    if rc:
        raise subprocess.CalledProcessError(rc, script)

def open_manifests(filenames):
    manifest_dir = os.path.dirname(os.path.realpath(__file__))
    manifest_dir = os.path.join(manifest_dir, 'manifest')
    for filename in filenames:
        manifest_path = os.path.join(manifest_dir, filename)
        if not os.path.exists(manifest_path):
            sys.stderr.write("Error: {0} does not exist\n".format(filename))
        else:
            with open(manifest_path) as f:
                script = '\n'.join(read_manifest(f))
                for output in execute(script):
                    print(output, end="")

def prompt():
    parser = argparse.ArgumentParser(description="J.A.R.V.I.S")
    parser.add_argument('--update',
                        nargs='*', metavar='manifest', help='Update manifests')
    args = parser.parse_args()
    if args.update is not None and len(args.update) > 0:
        open_manifests(args.update)
    else:
        parser.print_help()

if __name__ == "__main__":
    prompt()
