Vagrant.configure("2") do |config|
  config.vm.define "source", autostart: false do |source|
   source.vm.box = "{{ item.args.base_box }}"
	config.ssh.insert_key = false
  end
  config.vm.define "output" do |output|
   output.vm.box = "{{ item.args.pack_box }}"
	output.vm.box_url = "file://package.box"
	config.ssh.insert_key = false
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
