$provision = <<-SCRIPT
   sudo yum group install -y "Development Tools"
   sudo yum install vim
   git clone https://github.com/lenzomj/workspace.git
   cd workspace
   ./workspace update base
   rm ~/.bashrc
   ./workspace init
SCRIPT

Vagrant.configure("2") do |config|
   config.vm.provision "shell", inline: $provision, privileged: false
end
