---
# lonelybox :: tasks

  - name: Creating CentOS-7 mirror list directory
    become: true
    file:
      path: "{{ lonelybox.paths.mirrorlists }}"
      state: directory

  - name: Creating CentOS-7 base mirror list
    become: true
    copy:
      dest: "{{ lonelybox.paths.mirrorlists }}/mirror-base.list"
      content: |
        file://{{ box_gapmirror_uri }}/mirror.centos.org/centos/$releasever/os/$basearch/
        {{ box_netmirror_uri }}/mirror.centos.org/centos/$releasever/os/$basearch/

  - name: Adding CentOS-7 base repository
    become: true
    yum_repository:
      name: mirror-base
      description: CentOS-7 - Local Base
      file: lonelybox_mirrors
      mirrorlist: "file://{{ lonelybox.paths.mirrorlists }}/mirror-base.list"
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      gpgcheck: true

  - name: Creating CentOS-7 updates mirror list
    become: true
    copy:
      dest: "{{ lonelybox.paths.mirrorlists }}/mirror-updates.list"
      content: |
        file://{{ box_gapmirror_uri }}/mirror.centos.org/centos/$releasever/updates/$basearch/
        {{ box_netmirror_uri }}/mirror.centos.org/centos/$releasever/updates/$basearch/

  - name: Adding CentOS-7 updates repository
    become: true
    yum_repository:
      name: mirror-updates
      description: CentOS-7 - Local Updates
      file: lonelybox_mirrors
      mirrorlist: "file://{{ lonelybox.paths.mirrorlists }}/mirror-updates.list"
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      gpgcheck: true

  - name: Creating CentOS-7 extras mirror list
    become: true
    copy:
      dest: "{{ lonelybox.paths.mirrorlists }}/mirror-extras.list"
      content: |
        file://{{ box_gapmirror_uri }}/mirror.centos.org/centos/$releasever/extras/$basearch/
        {{ box_netmirror_uri }}/mirror.centos.org/centos/$releasever/extras/$basearch/

  - name: Adding CentOS-7 extras repository
    become: true
    yum_repository:
      name: mirror-extras
      description: CentOS-7 - Local Extras
      file: lonelybox_mirrors
      mirrorlist: "file://{{ lonelybox.paths.mirrorlists }}/mirror-extras.list"
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      gpgcheck: true

  - name: Creating CentOS-7 SCLo mirror list
    become: true
    copy:
      dest: "{{ lonelybox.paths.mirrorlists }}/mirror-sclo-rh.list"
      content: |
        file://{{ box_gapmirror_uri }}/mirror.centos.org/centos/$releasever/sclo/$basearch/rh/
        {{ box_gapmirror_uri }}/mirror.centos.org/centos/$releasever/sclo/$basearch/rh/

  - name: Adding CentOS-7 SCLo repository
    become: true
    yum_repository:
      name: mirror-centos-sclo-rh
      description: CentOS-7 - Local SCLo
      file: lonelybox_mirrors
      mirrorlist: "file://{{ lonelybox.paths.mirrorlists }}/mirror-sclo-rh.list"
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
      gpgcheck: true

  - name: Creating EPEL-7 mirror list
    become: true
    copy:
      dest: "{{ lonelybox.paths.mirrorlists }}/mirror-epel.list"
      content: |
        file://{{ box_gapmirror_uri }}/mirror.centos.org/fedora-epel/$releasever/$basearch/
        {{ box_gapmirror_uri }}/mirror.centos.org/fedora-epel/$releasever/$basearch/

  - name: Adding EPEL-7 repository
    become: true
    yum_repository:
      name: mirror-epel
      description: EPEL-7 - Local EPEL
      file: lonelybox_mirrors
      mirrorlist: "file://{{ lonelybox.paths.mirrorlists }}/mirror-epel.list"
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
      gpgcheck: true

  - name: Adding extra CentOS-7 repository keys
    become: true
    vars:
      ansible_python_interpreter: "/usr/bin/env python"
    package:
      name:
        - centos-release-scl
        - epel-release
      state: present

  - name: Verifying base packages
    become: true
    vars:
      ansible_python_interpreter: "/usr/bin/env python"
    package:
      name:
        - "@Development tools"
        - python
        - python3
        - libselinux-python3
        - git
        - rsync
        - curl
        - tree
      state: present

  - name: Updating installed packages to latest
    become: true
    vars:
      ansible_python_interpreter: "/usr/bin/env python"
    package:
      name: '*'
      state: latest
