---
# kubebox :: vars

kubebox_minikube_home: "{{ ansible_env.MINIKUBE_HOME | default(ansible_env.HOME + '/.minikube') }}"
kubebox_minikube_cache: "{{ kubebox_minikube_home }}/cache"

kubebox:
  resources:
    - resource: minikube-deb
      upstream: "https://storage.googleapis.com/minikube/releases/v1.16.0/minikube_1.16.0-1_amd64.deb"
      checksum: sha256:78a62f938932e1d6cafb5120f519505bc229a1cdcb5767e048fc4b729aebb6f6
      handlers: get and install on Debian

    - resource: minikube-rhel
      upstream: "https://storage.googleapis.com/minikube/releases/v1.16.0/minikube-1.16.0-0.x86_64.rpm"
      checksum: sha256:7c44daa4e46007ea06dd03085fc39e7e62e08d23f9eca9da35a5a9b9bdfbbb74
      handlers: get and install on RedHat

    - resource: minikube-iso
      upstream: "https://storage.googleapis.com/minikube/iso/minikube-v1.16.0.iso"
      checksum: sha256:acbd805831ad3afe8935c6e28888a414e9cde952afe5b574b9f44c853bde8814
      handlers: get and copy on Debian or RedHat
      args:
        dest: "{{ kubebox_minikube_cache }}/iso/"

    - resource: minikube-preloaded-images-k8s-docker
      upstream: "https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v8-v1.20.0-docker-overlay2-amd64.tar.lz4"
      checksum: sha256:6bc9dddb8eb580c08933d4b12ff68901635845f83420d75e0f2fd4bab6c5ea25
      handlers: get and copy on Debian or RedHat
      args:
        dest: "{{ kubebox_minikube_cache }}/preloaded-tarball/"

    - resource: kubectl
      upstream: "https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/linux/amd64/kubectl"
      checksum: sha256:a5895007f331f08d2e082eb12458764949559f30bcc5beae26c38f3e2724262c
      handlers: get and copy on Debian or RedHat
      args:
        dest: "{{ ansible_env.HOME }}/.local/bin"
        mode: "a+x"

    - resource: docker-compose
      upstream: "https://github.com/docker/compose/releases/download/1.28.0/docker-compose-linux-x86_64"
      checksum: sha256:07a5e4104ac6495603454ada9c053a79ac554f65df3ffc28e833b571f6c3e6d1
      handlers: get and copy on Debian
      args:
        dest: "{{ ansible_env.HOME }}/.local/bin/docker-compose"
        mode: "a+x"

      # TODO: migrate CentOS to docker-compose 1.28.0 after 1.28.x compatibility patch
    - resource: docker-compose
      upstream: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-linux-x86_64"
      checksum:
      handlers: get and copy on RedHat
      args:
        dest: "{{ ansible_env.HOME }}/.local/bin/docker-compose"
        mode: "a+x"

    - resource: postgres:latest
      upstream: "docker://docker.io/postgres:latest"
      handlers: skopeo-copy

    - resource: nginx:stable
      upstream: "docker://docker.io/nginx:stable"
      handlers: skopeo-copy

    - resource: centos:centos7
      upstream: "docker://docker.io/centos:centos7"
      handlers: skopeo-copy

    - resource: jenkins:lts
      upstream: "docker://docker.io/jenkins/jenkins:lts"
      handlers: skopeo-copy

    - resource: hello-world:latest
      upstream: "docker://docker.io/hello-world:latest"
      handlers: skopeo-copy
