---
# library :: clone-repositories

  - name: "Cloning repositories from {{ box_cache_path }}"
    git:
      repo: "{{ _cache_path }}"
      dest: "{{ item.clone }}"
      remote: origin
      clone: yes
      update: no
    vars:
      _host: "{{ item.upstream | urlsplit('hostname') }}"
      _path: "{{ item.upstream | urlsplit('path') }}"
      _cache_path: "{{ box_cache_path }}/{{ _host }}{{ _path }}"
    loop: "{{ repositories | selectattr('clone', 'defined') }}"

    # TODO: Check if remote already exists
  - name: Adding upstream remote
    command: "git remote add upstream {{ item.upstream }}"
    args:
      chdir: "{{ item.clone }}"
    ignore_errors: true
    loop: "{{ repositories | selectattr('clone', 'defined') }}"

  - name: Initializing repositories
    command: "{{ item.setup }}"
    args:
      chdir: "{{ item.clone }}"
    loop: "{{ repositories
              | selectattr('clone', 'defined')
              | selectattr('setup', 'defined')
           }}"
