---
# library :: encrypt-vault

  - name: "Obtaining {{ vault_name }} vault data"
    no_log: true
    pause:
      prompt: "Value of {{ vault_var }}"
      echo: false
    register: _variables
    loop_control:
      loop_var: vault_var
    loop: "{{ vault_vars }}"

  - name: "Encrypting {{ vault_name }} vault data"
    no_log: true
    command: >
      ansible-vault encrypt_string {{ item.user_input }} \
                    --vault-id {{ vault_name }}@{{ box_vault_key_path }} \
                    --name {{ item.vault_var }}
    register: _ansible_vault_output
    loop: "{{ _variables.results }}"

  - name: "Stashing encrypted {{ vault_name }} vault data in {{ box_local_vault_path }}"
    no_log: true
    blockinfile:
      backup: yes
      path: "{{ box_local_vault_path }}"
      marker: "# {mark} {{ vault_name }}:{{ item.key }}"
      block: "{{ item.value.stdout }}"
    with_dict: "{{ dict(vault_vars | zip(_ansible_vault_output.results)) }}"
