---
# library :: encrypt-vault

  - name: "Confirming {{ vault_name }} vault encryption task"
    pause:
      prompt: |

        Encrypt vault
        -------------
        > Name:  {{ vault_name }}
        > Vars:  {{ vault_vars }}

        *Paths*
        > Keys:  {{ box_vault_key_path }}
        > Vault: {{ box_local_vault_path }}

        {% if ansible_env.ANSIBLE_VAULT_PASSWORD_FILE is defined %}
        *Warnings*
        Environment variable ANSIBLE_VAULT_PASSWORD_FILE is set.
        Only use the explict --vault-password-file option for this task.

        bash$ unset ANSIBLE_VAULT_PASSWORD_FILE
        bash$ ansible-playbook --vault-password-file={{ box_vault_key_path }}
        {% endif %}
        Proceed (Yes or No?)

      echo: true
    register: _proceed

  - name: "Obtaining {{ vault_name }} vault data"
    when: ( _proceed.user_input | bool )
    no_log: true
    pause:
      prompt: "Value of {{ vault_var }}"
      echo: false
    register: _variables
    loop_control:
      loop_var: vault_var
    loop: "{{ vault_vars }}"

  - name: "Encrypting {{ vault_name }} vault data"
    when: ( _proceed.user_input | bool )
    no_log: true
    command: >
      ansible-vault encrypt_string {{ item.user_input }} \
                    --vault-id {{ vault_name }}@{{ box_vault_key_path }} \
                    --name {{ item.vault_var }}
    register: _ansible_vault_output
    loop: "{{ _variables.results }}"

  - name: "Stashing encrypted {{ vault_name }} vault data in {{ box_local_vault_path }}"
    when:  ( _proceed.user_input | bool )
    no_log: true
    blockinfile:
      backup: yes
      path: "{{ box_local_vault_path }}"
      marker: "# {mark} {{ vault_name }}:{{ item.key }}"
      block: "{{ item.value.stdout }}"
    with_dict: "{{ dict(vault_vars | zip(_ansible_vault_output.results)) }}"
