---
# library :: fetch-resources

  - name: "Creating cache directories as required"
    no_log: true
    when:
      - ( box_has_internet or box_has_mirror )
      - ( 'get' in box_fetch_allowlist )
    file:
      path: "{{ _full_path | dirname }}"
      state: directory
    vars:
      _host: "{{ _rcs.upstream | urlsplit('hostname') }}"
      _path: "{{ _rcs.upstream | urlsplit('path') }}"
      _cache_path: "{{ _rcs.args.cache | default(box_local_cache_path) }}"
      _full_path: "{{ _cache_path }}/{{ _host }}{{ _path }}"
    loop_control:
      loop_var: _rcs
    loop: "{{ resources }}"

  - name: "Fetching public web resources from upstream"
    when:
      - ( box_has_internet )
      - ( 'get' in box_fetch_allowlist )
    get_url:
      url: "{{ _rcs.upstream }}"
      dest: "{{ _dest }}"
      checksum: "{{ _rcs.checksum }}"
    vars:
      _host: "{{ _rcs.upstream | urlsplit('hostname') }}"
      _path: "{{ _rcs.upstream | urlsplit('path') }}"
      _cache_path: "{{ _rcs.args.cache | default(box_local_cache_path) }}"
      _dest: "{{ _cache_path }}/{{ _host }}{{ _path }}"
    loop_control:
      loop_var: _rcs
    loop: "{{ resources
              | selectattr('handlers', 'search', 'get')
              | selectattr('args.password', 'undefined')
           }}"

  - name: "Fetching password-protected web resources from upstream"
    no_log: true
    when:
      - ( box_has_internet )
      - ( 'get' in box_fetch_allowlist )
    get_url:
      url: "{{ _rcs.upstream }}"
      url_username: "{{ _rcs.args.username }}"
      url_password: "{{ _rcs.args.password }}"
      dest: "{{ _dest }}"
      checksum: "{{ _rcs.checksum }}"
    vars:
      _host: "{{ _rcs.upstream | urlsplit('hostname') }}"
      _path: "{{ _rcs.upstream | urlsplit('path') }}"
      _cache_path: "{{ _rcs.args.cache | default(box_local_cache_path) }}"
      _dest: "{{ _cache_path }}/{{ _host }}{{ _path }}"
    loop_control:
      loop_var: _rcs
    loop: "{{ resources
              | selectattr('handlers', 'search', 'get')
              | selectattr('args.password', 'defined')
           }}"

  - name: "Fetching web resources from mirror"
    when:
      - ( box_has_mirror and not box_has_internet )
      - ( 'get' in box_fetch_allowlist )
      - ( _url != _dest )
    get_url:
      url: "file://{{ _url }}"
      dest: "{{ _dest }}"
      checksum: "{{ _rcs.checksum }}"
    vars:
      _host: "{{ _rcs.upstream | urlsplit('hostname') }}"
      _path: "{{ _rcs.upstream | urlsplit('path') }}"
      _mirror_path: "{{ item.args.mirror | default(box_mirror_uri) }}"
      _cache_path: "{{ _rcs.args.cache | default(box_local_cache_path) }}"
      _url: "{{ _mirror_path }}/{{ _host }}{{ _path }}"
      _dest: "{{ _cache_path }}/{{ _host }}{{ _path }}"
    loop_control:
      loop_var: _rcs
      label: "{{ _dest }}"
    loop: "{{ resources
              | selectattr('handlers', 'search', 'get')
           }}"

  - name: "Fetching public docker resources from upstream"
    when:
      - ( box_has_internet )
      - ( box_has_skopeo )
      - ( 'get' in box_fetch_allowlist )
    shell: |
      if [[ ! -f "{{ _dest }}" ]]; then
        skopeo --insecure-policy copy {{ _src }} \
        docker-archive:{{ _dest }}:{{ _rcs.resource }}
      fi
    args:
      executable: "/bin/bash"
    vars:
      _host: "{{ _rcs.upstream | urlsplit('hostname') }}"
      _path: "{{ _rcs.upstream | urlsplit('path') | dirname }}"
      _cache_path: "{{ _rcs.args.cache | default(box_local_cache_path) }}"
      _src: "{{ _rcs.upstream }}"
      _filename: "{{ _rcs.upstream |  replace(':','_') | basename }}.tar"
      _dest: "{{ _cache_path }}/{{ _host }}{{ _path }}/{{ _filename }}"
    loop_control:
      loop_var: _rcs
      label: "{{ _dest }}"
    loop: "{{ resources
              | selectattr('handlers', 'search', 'skopeo-copy')
              | selectattr('args.password', 'undefined')
           }}"

  - name: "Fetching password-protected docker resources from upstream"
    no_log: true
    when:
      - ( box_has_internet )
      - ( box_has_skopeo )
      - ( 'get' in box_fetch_allowlist )
    shell: |
      if [[ ! -f "{{ _dest }}" ]]; then
        skopeo --insecure-policy copy --src-creds '{{ _creds }}' {{ _src }} \
        docker-archive:{{ _dest }}:{{ _rcs.resource }}
      fi
    args:
      executable: "/bin/bash"
    vars:
      _host: "{{ _rcs.upstream | urlsplit('hostname') }}"
      _path: "{{ _rcs.upstream | urlsplit('path') | dirname }}"
      _cache_path: "{{ _rcs.args.cache | default(box_local_cache_path) }}"
      _creds: "{{ _rcs.args.username }}:{{ _rcs.args.password }}"
      _src: "{{ _rcs.upstream }}"
      _filename: "{{ _rcs.upstream |  replace(':','_') | basename }}.tar"
      _dest: "{{ _cache_path }}/{{ _host }}{{ _path }}/{{ _filename }}"
    loop_control:
      loop_var: _rcs
      label: "{{ _dest }}"
    loop: "{{ resources
              | selectattr('handlers', 'search', 'skopeo-copy')
              | selectattr('args.password', 'defined')
           }}"
