---
# library :: fetch-pypackages

  - name: Creating cache directories as required
    when:
      - ( box_has_internet or box_has_mirror )
      - ( 'pip' in box_fetch_allowlist )
    file:
      path: "{{ box_local_cache_path }}/pypi.org"
      state: directory

  - name: Finding specified python package requirements file
    when:
      - ( box_has_internet or box_has_mirror )
      - ( 'pip' in box_fetch_allowlist )
    stat:
      path: "{{ a_requirements_file }}"
    register: _reqs
    failed_when: (not _reqs.stat.exists)

  - name: >
      Fetching python packages from
      {{ box_has_internet | ternary('pypi.org', box_mirror_uri) }}
    when:
      - ( box_has_internet or box_has_mirror )
      - ( 'pip' in box_fetch_allowlist )
    command: "{{ _python }} -m pip download {{ _opts }} -r {{ _reqs.stat.path }}"
    args:
      chdir: "{{ box_local_cache_path }}/pypi.org"
    vars:
      _python: "{{ ansible_python_interpreter }}"
      _from_mirror: "--no-index --find-links={{ box_mirror_uri }}/pypi.org"
      _opts: "{{ box_has_internet | ternary('', _from_mirror) }}"
    register: _result
    changed_when: (_result.stdout | regex_search('Saved'))
