---
# library :: fetch-resources

  - name: Creating cache directories as required
    when:
      - box_allow_fetch
      - box_has_internet or box_has_mirror
    file:
      path: "{{ _cache_path | dirname }}"
      state: directory
    vars:
      _host: "{{ item.upstream | urlsplit('hostname') }}"
      _path: "{{ item.upstream | urlsplit('path') }}"
      _cache_path: "{{ box_cache_path }}/{{ _host }}{{ _path }}"
    loop: "{{ resources }}"

  - name: >
      Fetching resources from
      {{ box_has_internet | ternary('upstream', box_mirror_uri) }}
    when:
      - box_allow_fetch
      - box_has_internet or box_has_mirror
    get_url:
      url: "{{ box_has_internet | ternary(item.upstream, _mirror_path) }}"
      dest: "{{ _cache_path }}"
      checksum: "{{ item.checksum }}"
    vars:
      _host: "{{ item.upstream | urlsplit('hostname') }}"
      _path: "{{ item.upstream | urlsplit('path') }}"
      _cache_path: "{{ box_cache_path }}/{{ _host }}{{ _path }}"
      _mirror_path: "{{ box_mirror_uri }}/{{ _host }}{{ _path }}"
    loop: "{{ resources }}"
