---
# library :: sync-mirror

  - name: Creating cache directories as required
    when: (box_has_internet)
    file:
      path: "{{ _cache_path | dirname }}"
      state: directory
    vars:
      _host: "{{ item.resource }}"
      _path: "{{ item.upstream | urlsplit('path') }}"
      _cache_path: "{{ box_cache_path }}/{{ _host }}{{ _path }}"
    loop: "{{ mirrors }}"

  - name: Syncing mirrors from upstream
    when: (box_has_internet)
    command: "rsync -avSHP --no-motd --delete {{ item.upstream }} {{ _local }}"
    vars:
      _host: "{{ item.resource }}"
      _path: "{{ item.upstream | urlsplit('path') }}"
      _local: "{{ box_cache_path }}/{{ _host }}{{ _path | dirname }}"
    loop: "{{ mirrors  }}"
