---
# sandbox :: fetch

  - name: Fetching sandbox repositories from an upstream source
    import_role:
      name: library
      tasks_from: fetch-repositories
    vars:
      a_repository_list: "{{ sandbox_repositories }}"

  - name: Fetching sandbox resources from an upstream source
    import_role:
      name: library
      tasks_from: fetch-resources
    vars:
      a_resource_list: "{{ sandbox_managed_packages +
                           sandbox_local_packages +
                           sandbox_resources }}"
