---
# sandbox :: fetch

  - name: Fetching sandbox repositories from an upstream source
    when: (box_has_internet or box_has_mirror)
    git:
      repo: "{{ lookup('dict', item).value.upstream }}"
      dest: "{{ box_cache_path }}/{{ lookup('dict', item).value.mirror }}"
      bare: yes
      clone: yes
      update: yes
    loop: "{{ sandbox_repositories}}"

  - name: Fetching sandbox resources from an upstream source
    import_role:
      name: library
      tasks_from: fetch-resources
    vars:
      a_resource_list: "{{ sandbox_managed_packages +
                           sandbox_local_packages +
                           sandbox_resources }}"
