---
# sandbox role (fetch)

  - name: Fetching sandbox repositories from an upstream source
    when: (box_has_internet or box_has_mirror)
    git:
      repo: "{{ lookup('dict', item).value.upstream }}"
      dest: "{{ box_cache_path }}/{{ lookup('dict', item).value.mirror }}"
      bare: yes
      clone: yes
      update: yes
    loop: "{{ sandbox_repositories}}"

  - name: Creating cache directories as required
    when: (box_has_internet or box_has_mirror)
    file:
      path: "{{ _cache_dir }}"
      state: directory
    vars:
      _upstream: "{{ lookup('dict', item).value.upstream }}"
      _cache_path: "{{ box_cache_path }}/{{ _upstream | urlsplit('path') }}"
      _cache_dir: "{{ _cache_path | dirname }}"
    loop: "{{ sandbox_managed_packages +
              sandbox_other_packages +
              sandbox_resources }}"

  - name: Fetching sandbox packages and resources from an upstream source
    when: (box_has_internet or box_has_mirror)
    get_url:
      url: "{{ _upstream }}"
      dest: "{{ _cache_path }}"
      checksum: "{{ lookup('dict', item).value.checksum }}"
    vars:
      _upstream: "{{ lookup('dict', item).value.upstream }}"
      _cache_path: "{{ box_cache_path }}/{{ _upstream | urlsplit('path') }}"
      _mirror_path: "{{ box_mirror_path }}/{{ _upstream | urlsplit('path') }}"
      _uri: "{{ box_has_internet | ternary(_upstream, _mirror_path) }}"
    loop: "{{ sandbox_managed_packages +
              sandbox_other_packages +
              sandbox_resources }}"

