---
# sandbox :: generate-boxfactory

  - name: "Creating vagrant {{ item.args.template }} factory"
    file:
      path: "{{ box_local_path }}/sandbox/factory/{{ item.args.template }}"
      state: directory

  - name: "Generating vagrant {{ item.args.template }} factory configurations"
    template:
      src: "{{ file.src }}"
      dest: "{{ _factory_path }}/{{ item.args.template }}/{{ file.path }}"
    vars:
      _factory_path: "{{ box_local_path }}/sandbox/factory"
    loop_control:
      loop_var: file
    with_filetree: "templates/{{ item.args.template }}"
