---
# sandbox :: generate-boxfactory

  - name: "Creating vagrant {{ _rcs.args.template }} factory"
    file:
      path: "{{ box_local_path }}/sandbox/factory/{{ _rcs.args.template }}"
      state: directory

  - name: "Generating vagrant {{ _rcs.args.template }} factory configurations"
    template:
      src: "{{ file.src }}"
      dest: "{{ _factory_path }}/{{ _rcs.args.template }}/{{ file.path }}"
    vars:
      _factory_path: "{{ box_local_path }}/sandbox/factory"
    loop_control:
      loop_var: file
    with_filetree: "templates/{{ _rcs.args.template }}"
