---

  - name: Installing other RHEL packages
    become: true
    when: box_distro in _required
    package:
      name: "{{ _cache_path }}"
      state: present
    vars:
      _required: "{{ lookup('dict', item).value.required | default([ ],true) }}"
      _pkg_name: "{{ lookup('dict', item).key }}"
      _upstream: "{{ lookup('dict', item).value.upstream }}"
      _cache_path: "{{ box_cache_path }}/{{ _upstream | urlsplit('path') }}"
    loop: "{{ sandbox_other_packages }}"
