---
# sandbox :: main

  - include: fetch.yml

  - name: Installing local packages
    import_role:
      name: library
      tasks_from: install-local
    vars:
      a_local_package_list: "{{ sandbox_local_packages }}"

  - name: Listing vagrant base boxes
    command: "vagrant box list"
    register: _vagrant_boxes
    changed_when: false
    failed_when: (_vagrant_boxes.rc != 0)

  - name: Installing new vagrant base boxes
    when: (not _box_exists)
    shell: "vagrant box add --force {{ _box_name }} {{ _cache_path }}"
    vars:
      _box_name: "{{ lookup('dict', item).key.split('-')[2] | lower }}"
      _box_exists: "{{ _vagrant_boxes.stdout | regex_search(_box_name) }}"
      _upstream: "{{ lookup('dict', item).value.upstream }}"
      _cache_path: "{{ box_cache_path }}/{{ _upstream | urlsplit('path') }}"
    loop: "{{ sandbox_resources | select('search', 'vagrant-box') | list }}"
