---
# sandbox role (main)

  - name: Fetching sandbox packages and resources from an upstream source
    include: fetch.yml

  - name: Installing packages (Debian)
    when: ansible_facts['os_family'] == "Debian"
    include: install-deb.yml

  - name: Installing packages (RHEL)
    when: ansible_facts['os_family'] == "RedHat"
    include: install-rpm.yml

  - name: Listing vagrant base boxes
    command: "vagrant box list"
    register: _vagrant_boxes
    changed_when: false
    failed_when: (_vagrant_boxes.rc != 0)

  - name: Installing new vagrant base boxes
    when: (not _box_exists)
    shell: "vagrant box add --force {{ _box_name }} {{ _cache_path }}"
    vars:
      _box_name: "{{ lookup('dict', item).key.split('-')[2] | lower }}"
      _box_exists: "{{ _vagrant_boxes.stdout | regex_search(_box_name) }}"
      _upstream: "{{ lookup('dict', item).value.upstream }}"
      _cache_path: "{{ box_cache_path }}/{{ _upstream | urlsplit('path') }}"
    loop: "{{ sandbox_resources | select('search', 'vagrant-box') | list }}"
