---
# sandbox :: main

  - include: fetch.yml

  - import_tasks: "{{ box_task_library }}/install-resources.yml"
    vars:
      resources: "{{ sandbox.resources }}"

  - name: Listing vagrant base boxes
    command: "vagrant box list"
    register: _vagrant_boxes
    changed_when: false
    failed_when: (_vagrant_boxes.rc != 0)

  - name: Installing new vagrant base boxes
    when: (not _box_exists)
    shell: "vagrant box add --force {{ _base_box }} {{ _cache_path }}"
    vars:
      _base_box: "{{ _rcs.args.base_box }}"
      _box_exists: "{{ _vagrant_boxes.stdout | regex_search(_base_box) }}"
      _host: "{{ _rcs.upstream | urlsplit('hostname') }}"
      _path: "{{ _rcs.upstream | urlsplit('path') }}"
      _cache_path: "{{ box_local_cache_path }}/{{ _host }}{{ _path }}"
    loop_control:
      loop_var: _rcs
    loop: "{{ sandbox.resources
              | selectattr('handlers', 'defined')
              | selectattr('handlers', 'search', 'vagrant-add')
           }}"

  - name: Creating vagrant box factory
    include_tasks: generate-boxfactory.yml
    loop_control:
      loop_var: _rcs
    loop: "{{ sandbox.resources
              | selectattr('handlers', 'defined')
              | selectattr('handlers', 'search', 'vagrant-package')
           }}"


