---
# devbox :: fetch-pypackages

  - name: Creating cache directories as required
    file:
      path: "{{ box_cache_path }}/pypi.org"
      state: directory

  - name: >
      Fetching python packages from
      {{ box_has_internet | ternary('pypi.org', box_mirror_path) }}
    when: (box_has_internet or box_has_mirror)
    command: "{{ _python }} -m pip download {{ _opts }} -r {{ _reqs.stat.path }}"
    args:
      chdir: "{{ box_cache_path }}/pypi.org"
    vars:
      _python: "{{ ansible_python_interpreter }}"
      _from_mirror: "--no-index --find-links={{ box_mirror_path }}/pypi.org"
      _reqs: "{{ a_requirements_file }}"
      _opts: "{{ box_has_internet | ternary('', _from_mirror) }}"
    register: _result
    changed_when: (_result.stdout | regex_search('Saved'))
