---
# kubebox-centos :: tasks

  - name: (CentOS) Installing docker and friends
    become: true
    vars:
      ansible_python_interpreter: "/usr/bin/env python"
    package:
      name:
        - skopeo
        - docker
        - podman
        - buildah
      state: present

  - name: (CentOS) Creating docker group
    become: true
    group:
      name: docker
      state: present
