---
# kubebox-debian :: tasks

  - name: (Debian) Adding kubic repository key
    become: true
    apt_key:
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/Release.key"
      state: present

  - name: (Debian) Adding kubic repository to sources list
    become: true
    apt_repository:
      repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /"
      state: present

  - name: (Debian) Adding docker repository key
    become: true
    apt_key:
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: (Debian) Adding docker repository to sources list
    become: true
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present

  - name: (Debian) Installing docker and friends
    become: true
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - skopeo
      - docker-ce

  - name: Creating docker group
    become: true
    group:
      name: docker
      state: present
