---
# kubebox-centos :: tasks

  - name: (CentOS) Installing docker and friends
    become: true
    vars:
      ansible_python_interpreter: "/usr/bin/env python"
    package:
      name:
        - skopeo
        - docker
        - podman
        - buildah
      state: present

  - name: (CentOS) Creating docker group
    become: true
    group:
      name: docker
      state: present

    # firewall-cmd \
    #   --permanent \
    #   --add-rich-rule="rule family='ipv4' source address='192.168.99.0/24' accept"
    # firewall-cmd --list-rich-rules
  - name: (CentOS) Configuring firewall settings
    become: true
    vars:
      ansible_python_interpreter: "/usr/bin/env python"
    ansible.posix.firewalld:
      rich_rule: "rule family='ipv4' source address='192.168.99.0/24' accept"
      permanent: true
      immediate: true
      state: disabled
