---
# kubebox :: tasks

  - include: "fetch.yml"

  - include: "kubebox-debian.yml"
    when: ((ansible_distribution == "Ubuntu" and
            ansible_distribution_major_version | int == 18) or
           (ansible_distribution == "Linux Mint" and
            ansible_distribution_major_version | int == 19))

  - import_tasks: "{{ box_task_library }}/install-resources.yml"
    vars:
      resources: "{{ kubebox.resources }}"
