---
# devbox :: vars

devbox:
  resources: # {{{
    - resource: cascadia-font
      upstream: "https://github.com/microsoft/cascadia-code/releases/download/v2009.22/CascadiaCode-2009.22.zip"
      checksum: sha256:801bcc94b79ae46bc573c9c07feb44d581e12d15f79b176be165f00f8fdf9846
      handlers: get

  # }}}

  repositories: # {{{
    - repository: dotfiles
      upstream: https://github.com/lenzomj/dotfiles.git
      args:
        clone: "{{ box_local_path }}/dotfiles"
        track: "{{ box_local_path }}/dotfiles"
        setup: "./install.sh {{ ansible_env.HOME }}"

    - repository: workspace
      upstream: https://github.com/lenzomj/workspace.git
      args:
        track: "{{ box_workspace_path }}"

    - repository: ctrlp.vim
      upstream: https://github.com/ctrlpvim/ctrlp.vim.git

    - repository: lightline.vim
      upstream: https://github.com/itchyny/lightline.vim.git

    - repository: nerdtree
      upstream: https://github.com/preservim/nerdtree.git

    - repository: tabular
      upstream: https://github.com/godlygeek/tabular.git

    - repository: vim-anyfold
      upstream: https://github.com/pseewald/vim-anyfold.git

    - repository: vim-colorschemes
      upstream: https://github.com/flazz/vim-colorschemes.git

    - repository: vim-gitgutter
      upstream: https://github.com/airblade/vim-gitgutter.git

    - repository: vim-markdown
      upstream: https://github.com/plasticboy/vim-markdown.git

    - repository: vim-pencil
      upstream: https://github.com/reedes/vim-pencil.git

    - repository: vim-fugitive
      upstream: https://github.com/tpope/vim-fugitive.git

  # }}}
