---
# devbox :: vars

devbox_repositories:
  - dotfiles:
      upstream: ssh://git@github.com/lenzomj/dotfiles.git
      clone: "{{ box_workspace_path }}/dotfiles"
      setup: "./install.sh {{ ansible_env.HOME }}"

  - workspace:
      upstream: ssh://git@github.com/lenzomj/workspace.git

  - ctrlp.vim:
      upstream: ssh://git@github.com/ctrlpvim/ctrlp.vim.git

  - lightline.vim:
      upstream: ssh://git@github.com/itchyny/lightline.vim.git

  - nerdtree:
      upstream: ssh://git@github.com/preservim/nerdtree.git

  - tabular:
      upstream: ssh://git@github.com/godlygeek/tabular.git

  - vim-anyfold:
      upstream: ssh://git@github.com/pseewald/vim-anyfold.git

  - vim-colorschemes:
      upstream: ssh://git@github.com/flazz/vim-colorschemes.git

  - vim-gitgutter:
      upstream: ssh://git@github.com/airblade/vim-gitgutter.git

  - vim-markdown:
      upstream: ssh://git@github.com/plasticboy/vim-markdown.git

  - vim-pencil:
      upstream: ssh://git@github.com/reedes/vim-pencil.git
